apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-configserver-deployment
  labels:
    app: qualix-configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-configserver
  template:
    metadata:
      labels:
        app: qualix-configserver
    spec:
      containers:
      - name: qualix-configserver
        image: agnpacr.azurecr.io/springcloud/qualix-configserver
        ports:
        - containerPort: 8989
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: qualix-configmap
                key: SPRING_PROFILES_DEFAULT_ACTIVE
        imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpacr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-service-discovery-deployment
  labels:
    app: qualix-service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-service-discovery
  template:
    metadata:
      labels:
        app: qualix-service-discovery
    spec:
      containers:
        - name: qualix-service-discovery
          image: agnpacr.azurecr.io/springcloud/qualix-service-discovery
          ports:
            - containerPort: 8992
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_DEFAULT_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_CONFIG_IMPORT
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpacr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-auth-deployment
  labels:
    app: qualix-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-auth
  template:
    metadata:
      labels:
        app: qualix-auth
    spec:
      containers:
        - name: qualix-auth
          image: agnpacr.azurecr.io/springcloud/qualix-auth
          ports:
            - containerPort: 8990
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpacr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-device-deployment
  labels:
    app: qualix-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-device
  template:
    metadata:
      labels:
        app: qualix-device
    spec:
      containers:
        - name: qualix-device
          image: agnpacr.azurecr.io/springcloud/qualix-device
          ports:
            - containerPort: 8991
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpacr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-api-gateway-deployment
  labels:
    app: qualix-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-api-gateway
  template:
    metadata:
      labels:
        app: qualix-api-gateway
    spec:
      containers:
        - name: qualix-api-gateway
          image: agnpacr.azurecr.io/springcloud/qualix-api-gateway
          ports:
            - containerPort: 8993
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_DEFAULT_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpacr