apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-configserver-deployment
  labels:
    app: qualix-configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-configserver
  template:
    metadata:
      labels:
        app: qualix-configserver
    spec:
      containers:
        - name: qualix-configserver
          image: agnpacr.azurecr.io/springcloud/qualix-configserver
          ports:
            - containerPort: 8989
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_DEFAULT_ACTIVE
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpacr