apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-auth-deployment
  labels:
    app: qualix-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-auth
  template:
    metadata:
      labels:
        app: qualix-auth
    spec:
      containers:
        - name: qualix-auth
          image: agnpandora.azurecr.io/springcloud/qualix-auth-service
          ports:
            - containerPort: 8990
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpandora

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-assaying-deployment
  labels:
    app: qualix-assaying
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-assaying
  template:
    metadata:
      labels:
        app: qualix-assaying
    spec:
      containers:
        - name: qualix-assaying
          image: agnpandora.azurecr.io/springcloud/qualix-assaying-service
          ports:
            - containerPort: 8994
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpandora


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-device-deployment
  labels:
    app: qualix-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-device
  template:
    metadata:
      labels:
        app: qualix-device
    spec:
      containers:
        - name: qualix-device
          image: agnpandora.azurecr.io/springcloud/qualix-device-service
          ports:
            - containerPort: 8991
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpandora
