apiVersion: v1
kind: Service
metadata:
  name: qualix-configserver
spec:
  selector:
    #This defines which pods are going to be represented by this Service.
    #The sevice becomes a network endpoint for either other services
    #or may be external users to connect to (web browser)
    app: qualix-configserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
