apiVersion: v1
kind: Service
metadata:
  name: qualix-api-gateway
spec:
  selector:
    app: qualix-api-gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8993
      targetPort: 8993