apiVersion: v1
kind: Service
metadata:
  name: qualix-service-discovery
spec:
  selector:
    app: qualix-service-discovery
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8992
      targetPort: 8992