apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-auth-deployment
  labels:
    app: qualix-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-auth
  template:
    metadata:
      labels:
        app: qualix-auth
    spec:
      containers:
        - name: qualix-auth
          image: agnpacr.azurecr.io/springcloud/qualix-auth
          ports:
            - containerPort: 8990
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpacr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualix-device-deployment
  labels:
    app: qualix-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualix-device
  template:
    metadata:
      labels:
        app: qualix-device
    spec:
      containers:
        - name: qualix-device
          image: agnpacr.azurecr.io/springcloud/qualix-device
          ports:
            - containerPort: 8991
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: qualix-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          imagePullPolicy: Always
      imagePullSecrets:
        - name: agnpacr