apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  labels:
    app: zipkin
spec:
  replicas: 1
  selectors:
    matchLabels:
      app: zipkin
    template:
      metadata:
        labels:
          app: zipkin
      spec:
        containers:
          - name: zipkin
            image: openzipkin/zipkin
            ports:
              - containerPort: 9411
